// <auto-generated>
// This file was generated by a tool; you should avoid making direct changes.
// Output Name: CustomFieldTableSet
// </auto-generated>

#region Designer generated code
#nullable disable
using System;
using System.Collections.Generic;

using xpTURN.Protobuf;

using xpTURN.Common;
using xpTURN.MegaData;

namespace Tests.CustomField
{
    public partial class CustomFieldTableSet : TableSet
    {
        private CustomFieldTableSet() : base() { }
        public static CustomFieldTableSet Instance { get; } = new CustomFieldTableSet();

        #region Get.Method
        public CustomFieldDataTable GetCustomFieldDataTable() => GetTable(1) as CustomFieldDataTable;

        public CustomFieldData GetCustomFieldData(int id) => GetDataById(1, id) as CustomFieldData;
        public CustomFieldData GetCustomFieldData(string alias) => GetDataById(1, GetId(alias)) as CustomFieldData;
        #endregion

        #region Protected.Method
        override protected Table RawCreateTable(int tableId) => tableId switch
        {
            1 => new CustomFieldDataTable(),
            _ => null,
        };
        override protected SortedDictionary<string, int> TableAlias { get; } = new SortedDictionary<string, int>
        {
            { nameof(CustomFieldDataTable), 1 },
        };
        #endregion
    }
}
#nullable restore
#endregion
