// <auto-generated>
// This file was generated by a tool; you should avoid making direct changes.
// Output Name: AliasTableSet
// </auto-generated>

#region Designer generated code
#nullable disable
using System;
using System.Collections.Generic;

using xpTURN.Common;
using xpTURN.Protobuf;
using xpTURN.MegaData;

namespace Tests.Alias
{
    public partial class AliasTableSet : TableSet
    {
        private AliasTableSet() : base() { }
        public static AliasTableSet Instance { get; } = new AliasTableSet();

        #region Get.Method
        public DepthDataTable GetDepthDataTable() => GetTable(1) as DepthDataTable;

        public FirstData GetFirstData(string alias) => GetDataByAlias(1, alias) as FirstData;
        #endregion

        #region Protected.Method
        override protected Table RawCreateTable(int tableId) => tableId switch
        {
            1 => new DepthDataTable(),
            _ => null,
        };
        override protected SortedDictionary<string, int> TableAlias { get; } = new SortedDictionary<string, int>
        {
            { nameof(DepthDataTable), 1 },
        };
        #endregion
    }
}
#nullable restore
#endregion
