// <auto-generated>
// This file was generated by a tool; you should avoid making direct changes.
// Output Name: Sample1TableSet
// </auto-generated>

#region Designer generated code
#nullable disable
using System;
using System.Collections.Generic;

using xpTURN.Common;
using xpTURN.Protobuf;
using xpTURN.MegaData;

namespace Samples
{
    public partial class Sample1TableSet : TableSet
    {
        private Sample1TableSet() : base() { }
        public static Sample1TableSet Instance { get; } = new Sample1TableSet();

        #region Get.Method
        public BoxDataTable GetBoxDataTable() => GetTable(1) as BoxDataTable;
        public DepthDataTable GetDepthDataTable() => GetTable(2) as DepthDataTable;
        public DiceDataTable GetDiceDataTable() => GetTable(3) as DiceDataTable;
        public ItemDataTable GetItemDataTable() => GetTable(4) as ItemDataTable;
        public NumberDataTable GetNumberDataTable() => GetTable(6) as NumberDataTable;
        public NumbersDataTable GetNumbersDataTable() => GetTable(7) as NumbersDataTable;

        public BoxData GetBoxData(int id) => GetDataById(1, id) as BoxData;
        public BoxData GetBoxData(string alias) => GetDataById(1, GetId(alias)) as BoxData;
        public FirstData GetFirstData(int id) => GetDataById(2, id) as FirstData;
        public FirstData GetFirstData(string alias) => GetDataById(2, GetId(alias)) as FirstData;
        public DiceData GetDiceData(int id) => GetDataById(3, id) as DiceData;
        public DiceData GetDiceData(string alias) => GetDataById(3, GetId(alias)) as DiceData;
        public ItemData GetItemData(int id) => GetDataById(4, id) as ItemData;
        public ItemData GetItemData(string alias) => GetDataById(4, GetId(alias)) as ItemData;
        public NumberData GetNumberData(NumberType id) => GetDataById(6, (int)id) as NumberData;
        public NumbersData GetNumbersData(NumbersType id) => GetDataById(7, (int)id) as NumbersData;
        #endregion

        #region Protected.Method
        override protected Table RawCreateTable(int tableId) => tableId switch
        {
            1 => new BoxDataTable(),
            2 => new DepthDataTable(),
            3 => new DiceDataTable(),
            4 => new ItemDataTable(),
            5 => new LocaleDataTable(),
            6 => new NumberDataTable(),
            7 => new NumbersDataTable(),
            8 => new TextDataTable(),
            9 => new TranslatedDataTable(),
            _ => null,
        };
        override protected Data RawCreateData(int tableId) => tableId switch
        {
            5 => new TextDataTable(), // LocaleDataTable
            8 => new TextData(), // TextDataTable
            _ => null,
        };
        override protected SortedDictionary<string, int> TableAlias { get; } = new SortedDictionary<string, int>
        {
            { nameof(BoxDataTable), 1 },
            { nameof(DepthDataTable), 2 },
            { nameof(DiceDataTable), 3 },
            { nameof(ItemDataTable), 4 },
            { nameof(LocaleDataTable), 5 },
            { nameof(NumberDataTable), 6 },
            { nameof(NumbersDataTable), 7 },
            { nameof(TextDataTable), 8 },
            { nameof(TranslatedDataTable), 9 },
        };
        override protected bool IsOndemandTable(int tableId) => tableId switch
        {
            5 => true, // LocaleDataTable
            8 => true, // TextDataTable
            _ => false,
        };
        override protected bool IsWeakRefTable(int tableId) => tableId switch
        {
            5 => true, // LocaleDataTable
            8 => true, // TextDataTable
            _ => false,
        };
        #endregion
    }
}
#nullable restore
#endregion
