// <auto-generated>
// This file was generated by a tool; you should avoid making direct changes.
// Output Name: AllTypesTableSet
// </auto-generated>

#region Designer generated code
#nullable disable
using System;
using System.Collections.Generic;

using xpTURN.Common;
using xpTURN.Protobuf;
using xpTURN.MegaData;

namespace Tests.AllTypes
{
    public partial class AllTypesTableSet : TableSet
    {
        private AllTypesTableSet() : base() { }
        public static AllTypesTableSet Instance { get; } = new AllTypesTableSet();

        #region Get.Method
        public AllTypesDataTable GetAllTypesDataTable() => GetTable(1) as AllTypesDataTable;
        public EmptyDataTable GetEmptyDataTable() => GetTable(2) as EmptyDataTable;

        public AllTypesData GetAllTypesData(int id) => GetDataById(1, id) as AllTypesData;
        public AllTypesData GetAllTypesData(string alias) => GetDataById(1, GetId(alias)) as AllTypesData;
        public EmptyData GetEmptyData(int id) => GetDataById(2, id) as EmptyData;
        public EmptyData GetEmptyData(string alias) => GetDataById(2, GetId(alias)) as EmptyData;
        #endregion

        #region Protected.Method
        override protected Table RawCreateTable(int tableId) => tableId switch
        {
            1 => new AllTypesDataTable(),
            2 => new EmptyDataTable(),
            _ => null,
        };
        override protected SortedDictionary<string, int> TableAlias { get; } = new SortedDictionary<string, int>
        {
            { nameof(AllTypesDataTable), 1 },
            { nameof(EmptyDataTable), 2 },
        };
        #endregion
    }
}
#nullable restore
#endregion
