// <auto-generated>
// This file was generated by a tool; you should avoid making direct changes.
// Output Name: WeakRef1TableSet
// </auto-generated>

#region Designer generated code
#nullable disable
using System;
using System.Collections.Generic;

using xpTURN.Common;
using xpTURN.Protobuf;
using xpTURN.MegaData;

namespace Tests.WeakRef.Type1
{
    public partial class WeakRef1TableSet : TableSet
    {
        private WeakRef1TableSet() : base() { }
        public static WeakRef1TableSet Instance { get; } = new WeakRef1TableSet();

        #region Get.Method
        public NumberDataTable GetNumberDataTable() => GetTable(1) as NumberDataTable;
        public NumbersDataTable GetNumbersDataTable() => GetTable(2) as NumbersDataTable;
        public SampleDataTable GetSampleDataTable() => GetTable(3) as SampleDataTable;

        public NumberData GetNumberData(NumberType id) => GetDataById(1, (int)id) as NumberData;
        public NumbersData GetNumbersData(NumbersType id) => GetDataById(2, (int)id) as NumbersData;
        public SampleData GetSampleData(int id) => GetDataById(3, id) as SampleData;
        public SampleData GetSampleData(string alias) => GetDataById(3, GetId(alias)) as SampleData;
        #endregion

        #region Protected.Method
        override protected Table RawCreateTable(int tableId) => tableId switch
        {
            1 => new NumberDataTable(),
            2 => new NumbersDataTable(),
            3 => new SampleDataTable(),
            _ => null,
        };
        override protected Data RawCreateData(int tableId) => tableId switch
        {
            1 => new NumberData(), // NumberDataTable
            2 => new NumbersData(), // NumbersDataTable
            3 => new SampleData(), // SampleDataTable
            _ => null,
        };
        override protected SortedDictionary<string, int> TableAlias { get; } = new SortedDictionary<string, int>
        {
            { nameof(NumberDataTable), 1 },
            { nameof(NumbersDataTable), 2 },
            { nameof(SampleDataTable), 3 },
        };
        override protected bool IsOndemandTable(int tableId) => tableId switch
        {
            1 => true, // NumberDataTable
            2 => true, // NumbersDataTable
            3 => true, // SampleDataTable
            _ => false,
        };
        override protected bool IsWeakRefTable(int tableId) => tableId switch
        {
            1 => true, // NumberDataTable
            2 => true, // NumbersDataTable
            3 => true, // SampleDataTable
            _ => false,
        };
        #endregion
    }
}
#nullable restore
#endregion
