// <auto-generated>
// This file was generated by a tool; you should avoid making direct changes.
// Output Name: RefIdTableSet
// </auto-generated>

#region Designer generated code
#nullable disable
using System;
using System.Collections.Generic;

using xpTURN.Common;
using xpTURN.Protobuf;
using xpTURN.MegaData;

namespace Tests.RefId
{
    public partial class RefIdTableSet : TableSet
    {
        private RefIdTableSet() : base() { }
        public static RefIdTableSet Instance { get; } = new RefIdTableSet();

        #region Get.Method
        public BoxDataTable GetBoxDataTable() => GetTable(1) as BoxDataTable;
        public DiceDataTable GetDiceDataTable() => GetTable(2) as DiceDataTable;
        public ItemDataTable GetItemDataTable() => GetTable(3) as ItemDataTable;

        public BoxData GetBoxData(int id) => GetDataById(1, id) as BoxData;
        public BoxData GetBoxData(string alias) => GetDataById(1, GetId(alias)) as BoxData;
        public DiceData GetDiceData(int id) => GetDataById(2, id) as DiceData;
        public DiceData GetDiceData(string alias) => GetDataById(2, GetId(alias)) as DiceData;
        public ItemData GetItemData(int id) => GetDataById(3, id) as ItemData;
        public ItemData GetItemData(string alias) => GetDataById(3, GetId(alias)) as ItemData;
        #endregion

        #region Protected.Method
        override protected Table RawCreateTable(int tableId) => tableId switch
        {
            1 => new BoxDataTable(),
            2 => new DiceDataTable(),
            3 => new ItemDataTable(),
            4 => new LocaleDataTable(),
            5 => new TextDataTable(),
            6 => new TranslatedDataTable(),
            _ => null,
        };
        override protected Data RawCreateData(int tableId) => tableId switch
        {
            4 => new TextDataTable(), // LocaleDataTable
            5 => new TextData(), // TextDataTable
            _ => null,
        };
        override protected SortedDictionary<string, int> TableAlias { get; } = new SortedDictionary<string, int>
        {
            { nameof(BoxDataTable), 1 },
            { nameof(DiceDataTable), 2 },
            { nameof(ItemDataTable), 3 },
            { nameof(LocaleDataTable), 4 },
            { nameof(TextDataTable), 5 },
            { nameof(TranslatedDataTable), 6 },
        };
        override protected bool IsOndemandTable(int tableId) => tableId switch
        {
            4 => true, // LocaleDataTable
            5 => true, // TextDataTable
            _ => false,
        };
        override protected bool IsWeakRefTable(int tableId) => tableId switch
        {
            4 => true, // LocaleDataTable
            5 => true, // TextDataTable
            _ => false,
        };
        #endregion
    }
}
#nullable restore
#endregion
