// <auto-generated>
// This file was generated by a tool; you should avoid making direct changes.
// Output Name: ErrorsConvert1TableSet
// </auto-generated>

#region Designer generated code
#nullable disable
using System;
using System.Collections.Generic;

using xpTURN.Common;
using xpTURN.Protobuf;
using xpTURN.MegaData;

namespace Tests.Errors.Convert1
{
    public partial class ErrorsConvert1TableSet : TableSet
    {
        private ErrorsConvert1TableSet() : base() { }
        public static ErrorsConvert1TableSet Instance { get; } = new ErrorsConvert1TableSet();

        #region Get.Method
        public AllTypesDataTable GetAllTypesDataTable() => GetTable(1) as AllTypesDataTable;
        public BoxDataTable GetBoxDataTable() => GetTable(2) as BoxDataTable;
        public EmptyDataTable GetEmptyDataTable() => GetTable(3) as EmptyDataTable;
        public ItemDataTable GetItemDataTable() => GetTable(4) as ItemDataTable;

        public AllTypesData GetAllTypesData(int id) => GetDataById(1, id) as AllTypesData;
        public AllTypesData GetAllTypesData(string alias) => GetDataById(1, GetId(alias)) as AllTypesData;
        public BoxData GetBoxData(int id) => GetDataById(2, id) as BoxData;
        public BoxData GetBoxData(string alias) => GetDataById(2, GetId(alias)) as BoxData;
        public EmptyData GetEmptyData(int id) => GetDataById(3, id) as EmptyData;
        public EmptyData GetEmptyData(string alias) => GetDataById(3, GetId(alias)) as EmptyData;
        public ItemData GetItemData(int id) => GetDataById(4, id) as ItemData;
        public ItemData GetItemData(string alias) => GetDataById(4, GetId(alias)) as ItemData;
        #endregion

        #region Protected.Method
        override protected Table RawCreateTable(int tableId) => tableId switch
        {
            1 => new AllTypesDataTable(),
            2 => new BoxDataTable(),
            3 => new EmptyDataTable(),
            4 => new ItemDataTable(),
            _ => null,
        };
        override protected SortedDictionary<string, int> TableAlias { get; } = new SortedDictionary<string, int>
        {
            { nameof(AllTypesDataTable), 1 },
            { nameof(BoxDataTable), 2 },
            { nameof(EmptyDataTable), 3 },
            { nameof(ItemDataTable), 4 },
        };
        #endregion
    }
}
#nullable restore
#endregion
