// <auto-generated>
// This file was generated by a tool; you should avoid making direct changes.
// Output Name: ErrorsConvert2TableSet
// </auto-generated>

#region Designer generated code
#nullable disable
using System;
using System.Collections.Generic;

using xpTURN.Common;
using xpTURN.Protobuf;
using xpTURN.MegaData;

namespace Tests.Errors.Convert2
{
    public partial class ErrorsConvert2TableSet : TableSet
    {
        private ErrorsConvert2TableSet() : base() { }
        public static ErrorsConvert2TableSet Instance { get; } = new ErrorsConvert2TableSet();

        #region Get.Method
        public DepthDataTable GetDepthDataTable() => GetTable(1) as DepthDataTable;
        public LDepthDataTable GetLDepthDataTable() => GetTable(2) as LDepthDataTable;
        public NonDepthDataTable GetNonDepthDataTable() => GetTable(3) as NonDepthDataTable;

        public FirstData GetFirstData(int id) => GetDataById(1, id) as FirstData;
        public FirstData GetFirstData(string alias) => GetDataById(1, GetId(alias)) as FirstData;
        public LFirstData GetLFirstData(int id) => GetDataById(2, id) as LFirstData;
        public LFirstData GetLFirstData(string alias) => GetDataById(2, GetId(alias)) as LFirstData;
        public NonFirstData GetNonFirstData(int id) => GetDataById(3, id) as NonFirstData;
        public NonFirstData GetNonFirstData(string alias) => GetDataById(3, GetId(alias)) as NonFirstData;
        #endregion

        #region Protected.Method
        override protected Table RawCreateTable(int tableId) => tableId switch
        {
            1 => new DepthDataTable(),
            2 => new LDepthDataTable(),
            3 => new NonDepthDataTable(),
            _ => null,
        };
        override protected SortedDictionary<string, int> TableAlias { get; } = new SortedDictionary<string, int>
        {
            { nameof(DepthDataTable), 1 },
            { nameof(LDepthDataTable), 2 },
            { nameof(NonDepthDataTable), 3 },
        };
        #endregion
    }
}
#nullable restore
#endregion
