// <auto-generated>
// This file was generated by a tool; you should avoid making direct changes.
// Output Name: RepeatedTableSet
// </auto-generated>

#region Designer generated code
#nullable disable
using System;
using System.Collections.Generic;

using xpTURN.Common;
using xpTURN.Protobuf;
using xpTURN.MegaData;

namespace Tests.Repeated.V0
{
    public partial class RepeatedTableSet : TableSet
    {
        private RepeatedTableSet() : base() { }
        public static RepeatedTableSet Instance { get; } = new RepeatedTableSet();

        #region Get.Method
        public RepeatedDataTable GetRepeatedDataTable() => GetTable(1) as RepeatedDataTable;

        public RepeatedData GetRepeatedData(int id) => GetDataById(1, id) as RepeatedData;
        public RepeatedData GetRepeatedData(string alias) => GetDataById(1, GetId(alias)) as RepeatedData;
        #endregion

        #region Protected.Method
        override protected Table RawCreateTable(int tableId) => tableId switch
        {
            1 => new RepeatedDataTable(),
            _ => null,
        };
        override protected SortedDictionary<string, int> TableAlias { get; } = new SortedDictionary<string, int>
        {
            { nameof(RepeatedDataTable), 1 },
        };
        #endregion
    }
}
#nullable restore
#endregion
